### ISSUE TITLE
Add a button in the widget to export the data

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/widget-bandsplot#46]
I think this is mentioned by @giovannipizzi it is better to have a button in the widget where the RAW JSON data can be exported. Although the raw data is the input of the widget, when the widget is shown in the AiiDAlab app, user (especially the developer of the app) loses the chance to easily get the data out and sent it to the developers of this app to easily reproduce and debug.

**Comment by dou-du** [comment]
> I think this is mentioned by @giovannipizzi it is better to have a button in the widget where the RAW JSON data can be exported. Although the raw data is the input of the widget, when the widget is shown in the AiiDAlab app, user (especially the developer of the app) loses the chance to easily get the data out and sent it to the developers of this app to easily reproduce and debug.

This should be easy to be added. I will do it today.

**Comment by unkcpz** [comment]
Closed by #47
